### ISSUE TITLE
Appending original images?

### ISSUE THREAD

**Issue by zhanyuanucb** [tribhuvanesh/prediction-poisoning#2]
Seems like this line of code appends the original images to the _transferset_, and so I found a lot of identical images in the _transferset_. Isn't it supposed to be `X + delta_i`?
https://github.com/tribhuvanesh/prediction-poisoning/blob/9da6bcef17dc295b8ab0c94507a1d144d611311d/defenses/adversary/jacobian.py#L286

![Screenshot from 2020-11-03 15-53-56](https://user-images.githubusercontent.com/32000378/98053156-cb959f80-1dec-11eb-9729-5bf027c7a8a9.png)

**Comment by tribhuvanesh** [comment]
Thanks a lot for pointing this out! Just committed the patch.
